services:
  api: 
    build: ./back
    ports:
      - '5000:5000'
    environment:
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: db
      DB_PORT: "${DB_PORT}"
      SALT: "${SALT}"
      JWT_SECRET: "${JWT_SECRET}"
  db:
    image: redis:7.2
    restart: always
    command: redis-server --requirepass ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:6379"
